[language-server.rust-analyzer.config.check]
command = "clippy"

# Swift
[language-server.swiftlint]
command = "swiftlint"

[[language]]
name = "swift"
auto-format = true
language-servers = ["sourcekit-lsp", "swiftlint"]
formatter = { command = "swiftformat", args = [ "--config", "/Users/johnku/.swiftformat"]}
[language.debugger]
command = "lldb-dap"
name = "lldp-dap"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[grammar]]
name = "swift"
source = { git = "https://github.com/alex-pinkus/tree-sitter-swift", rev = "57c1c6d6ffa1c44b330182d41717e6fe37430704" }
